#ifndef __SETTINGS_H
#define __SETTINGS_H

#ifdef STM32F401xx
#include "stm32f4xx.h"

//Hardware configuration

//WIFI
#define WIFI_GPIO_CLK RCC_AHB1Periph_GPIOA
#define WIFI_MODULE_CLK_SETUP RCC_APB1PeriphClockCmd
#define WIFI_MODULE_CLK RCC_APB1Periph_USART2

#define WIFI_TX_PIN GPIO_Pin_2
#define WIFI_RX_PIN GPIO_Pin_3
#define WIFI_PORT GPIOA
#define WIFI_TX_PINSOURCE GPIO_PinSource2
#define WIFI_RX_PINSOURCE GPIO_PinSource3

#define WIFI_MODULE USART2
#define WIFI_MODULE_AF GPIO_AF_USART2
#define WIFI_IRQ USART2_IRQn
#define WIFI_TX_IT USART_IT_TC
#define WIFI_RX_IT USART_IT_RXNE
#define WIFI_IRQHandler USART2_IRQHandler

//GPS
#define GPS_GPIO_CLK RCC_AHB1Periph_GPIOC
#define GPS_MODULE_CLK_SETUP RCC_APB2PeriphClockCmd
#define GPS_MODULE_CLK RCC_APB2Periph_USART6

#define GPS_TX_PIN GPIO_Pin_6
#define GPS_RX_PIN GPIO_Pin_7
#define GPS_PORT GPIOC
#define GPS_TX_PINSOURCE GPIO_PinSource6
#define GPS_RX_PINSOURCE GPIO_PinSource7

#define GPS_MODULE USART6
#define GPS_MODULE_AF GPIO_AF_USART6
#define GPS_IRQ USART6_IRQn
#define GPS_TX_IT USART_IT_TC
#define GPS_RX_IT USART_IT_RXNE
#define GPS_IRQHandler USART6_IRQHandler

//GPRS
#define GPRS_GPIO_CLK RCC_AHB1Periph_GPIOA|RCC_AHB1Periph_GPIOB
#define GPRS_MODULE_CLK_SETUP RCC_APB2PeriphClockCmd
#define GPRS_MODULE_CLK RCC_APB2Periph_USART1

#define GPRS_TX_PIN GPIO_Pin_9
#define GPRS_RX_PIN GPIO_Pin_10
#define WIFI_RST_PIN GPIO_Pin_3
#define WIFI_MODE_PIN GPIO_Pin_5
#define GPRS_PORT GPIOA
#define WIFI_PORT2 GPIOB
#define GPRS_TX_PINSOURCE GPIO_PinSource9
#define GPRS_RX_PINSOURCE GPIO_PinSource10

#define GPRS_MODULE USART1
#define GPRS_MODULE_AF GPIO_AF_USART1
#define GPRS_IRQ USART1_IRQn
#define GPRS_TX_IT USART_IT_TC
#define GPRS_RX_IT USART_IT_RXNE
#define GPRS_IRQHandler USART1_IRQHandler

//LOCK
#define LOCK_GPIO_CLK RCC_AHB1Periph_GPIOC
#define LOCK_PIN GPIO_Pin_1
#define LOCK_PORT GPIOC

//RPI
#define RPI_GPIO_CLK RCC_AHB1Periph_GPIOA
#define RPI_MODULE_CLK_SETUP RCC_APB2PeriphClockCmd
#define RPI_MODULE_CLK RCC_APB2Periph_SPI1

#define RPI_NSS_PIN GPIO_Pin_4
#define RPI_SCK_PIN GPIO_Pin_5
#define RPI_MISO_PIN GPIO_Pin_6
#define RPI_MOSI_PIN GPIO_Pin_7
#define RPI_PORT GPIOA
#define RPI_NSS_PINSOURCE GPIO_PinSource4
#define RPI_SCK_PINSOURCE GPIO_PinSource5
#define RPI_MISO_PINSOURCE GPIO_PinSource6
#define RPI_MOSI_PINSOURCE GPIO_PinSource7

#define RPI_MODULE SPI1
#define RPI_MODULE_AF GPIO_AF_SPI1
#define RPI_IRQ SPI1_IRQn
#define RPI_TX_IT SPI_I2S_IT_TXE
#define RPI_RX_IT SPI_I2S_IT_RXNE
#define RPI_IRQHandler SPI1_IRQHandler

#endif
#endif /* __SETTINGS_H */
