#ifndef __SETTINGS_H
#define __SETTINGS_H

#ifdef STM32F401xx
#include "stm32f4xx.h"

//Hardware configuration

//GPS
#define GPS_GPIO_CLK RCC_AHB1Periph_GPIOA
#define GPS_MODULE_CLK_SETUP RCC_APB1PeriphClockCmd
#define GPS_MODULE_CLK RCC_APB1Periph_USART2

#define GPS_TX_PIN GPIO_Pin_2
#define GPS_RX_PIN GPIO_Pin_3
#define GPS_PORT GPIOA
#define GPS_TX_PINSOURCE GPIO_PinSource2
#define GPS_RX_PINSOURCE GPIO_PinSource3

#define GPS_MODULE USART2
#define GPS_MODULE_AF GPIO_AF_USART2
#define GPS_IRQ USART2_IRQn
#define GPS_TX_IT USART_IT_TC
#define GPS_RX_IT USART_IT_RXNE
#define GPS_IRQHandler USART2_IRQHandler

//WIFI
#define WIFI_GPIO_CLK RCC_AHB1Periph_GPIOC|RCC_AHB1Periph_GPIOB
#define WIFI_MODULE_CLK_SETUP RCC_APB2PeriphClockCmd
#define WIFI_MODULE_CLK RCC_APB2Periph_USART6

#define WIFI_TX_PIN GPIO_Pin_6
#define WIFI_RX_PIN GPIO_Pin_7
#define WIFI_RST_PIN GPIO_Pin_1
#define WIFI_MODE_PIN GPIO_Pin_2
#define WIFI_PORT GPIOC
#define WIFI_PORT2 GPIOB
#define WIFI_TX_PINSOURCE GPIO_PinSource6
#define WIFI_RX_PINSOURCE GPIO_PinSource7

#define WIFI_MODULE USART6
#define WIFI_MODULE_AF GPIO_AF_USART6
#define WIFI_IRQ USART6_IRQn
#define WIFI_TX_IT USART_IT_TC
#define WIFI_RX_IT USART_IT_RXNE
#define WIFI_IRQHandler USART6_IRQHandler

//GPRS
#define GPRS_GPIO_CLK RCC_AHB1Periph_GPIOA|RCC_AHB1Periph_GPIOC
#define GPRS_MODULE_CLK_SETUP RCC_APB2PeriphClockCmd
#define GPRS_MODULE_CLK RCC_APB2Periph_USART1

#define GPRS_TX_PIN GPIO_Pin_9
#define GPRS_RX_PIN GPIO_Pin_10
#define GPRS_PORT GPIOA
#define GPRS_START_PIN GPIO_Pin_0
#define GPRS_PORT2 GPIOC
#define GPRS_TX_PINSOURCE GPIO_PinSource9
#define GPRS_RX_PINSOURCE GPIO_PinSource10

#define GPRS_MODULE USART1
#define GPRS_MODULE_AF GPIO_AF_USART1
#define GPRS_IRQ USART1_IRQn
#define GPRS_TX_IT USART_IT_TC
#define GPRS_RX_IT USART_IT_RXNE
#define GPRS_IRQHandler USART1_IRQHandler

//LOCK
#define LOCK_GPIO_CLK RCC_AHB1Periph_GPIOC
#define LOCK_PIN GPIO_Pin_1
#define LOCK_PORT GPIOC

//RPI
#define RPI_GPIO_CLK RCC_AHB1Periph_GPIOB|RCC_AHB1Periph_GPIOC
#define RPI_MODULE_CLK_SETUP RCC_APB1PeriphClockCmd
#define RPI_MODULE_CLK RCC_APB1Periph_SPI2

#define RPI_NSS_PIN GPIO_Pin_12
#define RPI_SCK_PIN GPIO_Pin_10
#define RPI_MISO_PIN GPIO_Pin_2
#define RPI_MOSI_PIN GPIO_Pin_3
#define RPI_PORT GPIOB
#define RPI_PORT2 GPIOC
#define RPI_NSS_PINSOURCE GPIO_PinSource12
#define RPI_SCK_PINSOURCE GPIO_PinSource10
#define RPI_MISO_PINSOURCE GPIO_PinSource2
#define RPI_MOSI_PINSOURCE GPIO_PinSource3

#define RPI_MODULE SPI2
#define RPI_MODULE_AF GPIO_AF_SPI2
#define RPI_IRQ SPI2_IRQn
#define RPI_TX_IT SPI_I2S_IT_TXE
#define RPI_RX_IT SPI_I2S_IT_RXNE
#define RPI_IRQHandler SPI2_IRQHandler

//ACCGYRO
#define ACCGYRO_GPIO_CLK RCC_AHB1Periph_GPIOB
#define ACCGYRO_MODULE_CLK_SETUP RCC_APB1PeriphClockCmd
#define ACCGYRO_MODULE_CLK RCC_APB1Periph_I2C1

#define ACCGYRO_SDA_PIN GPIO_Pin_9
#define ACCGYRO_SCL_PIN GPIO_Pin_8
#define ACCGYRO_PORT GPIOB
#define ACCGYRO_SDA_PINSOURCE GPIO_PinSource9
#define ACCGYRO_SCL_PINSOURCE GPIO_PinSource8

#define ACCGYRO_MODULE I2C1
#define ACCGYRO_MODULE_AF GPIO_AF_I2C1
#define ACCGYRO_IRQ I2C1_EV_IRQn
//#define ACCGYRO_IRQ I2C1_ER_IRQn // en caso de error
#define ACCGYRO_TX_IT I2C_IT_TXE
#define ACCGYRO_RX_IT I2C_IT_RXNE
#define ACCGYRO_IRQHandler SPI2_IRQHandler

#endif
#endif /* __SETTINGS_H */
